# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname
url: "http://www.bitcoinabc.org"
baseurl: ""

# Name of website
title: Bitcoin ABC

# Short description of your site
description: Bitcoin ABC - Software for Bitcoin Cash nodes

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Latest Roadmap: "https://www.bitcoincash.org/roadmap/"
  Blog: "https://blog.bitcoinabc.org/"
  Download:
    - Releases: "releases/"
    - Source Code: "https://github.com/Bitcoin-ABC/bitcoin-abc"
  Documentation: "doc/"
  Developers:
    - Contributing: "CONTRIBUTING.html"
    - Code Coverage: "https://build.bitcoinabc.org/viewLog.html?buildId=lastSuccessful&buildTypeId=BitcoinABC_Master_BitcoinAbcMasterCoverage&tab=report__Root_Code_Coverage&guest=1"
    - Code Documentation: "doc/dev/"

supported-languages:
  en: "English"
  es: "Español"
  fr: "Français"
  jp: "日本語"
  ko: "한국어"
  nl: "Nederlands"
  pt: "Português"
  ru: "русский"
  zh_simple: "简体中文"
  zh_traditional: "繁体中文"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/img/avatar-icon-small.png"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Bitcoin ABC

# If you want to add a new link that isn't here, also edit the file _data/SocialNetworks.yml
social-network-links:
  email: "info@bitcoinabc.org"
  facebook: bitcoinabcorg
  github: bitcoin-abc
  twitter: bitcoin_abc
  linkedin: company/11232712
  youtube: BitcoinABC

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "bitcoinabc.org"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# --- Misc --- #
# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 30

# Number of announcements to appear on the front page
front_page_posts: 2

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  - scope:
      path: ""
      type: doc
    values:
      layout: doc
      category: rpc
  - scope:
      path: "" # all files
    values:
      layout: page

collections:
  doc:
    output: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - nginx.conf
  - Makefile
  - Rakefile

plugins:
  - jekyll-paginate
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: false

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
